ALTER TABLE `weixin_cashcouponhistory`
	DROP INDEX `INX_WEIXIN_CASHCOUPON_HUODONGID_RE_OPENID`,
	DROP INDEX `INX_WEIXIN_CASHCOUPONHISTORY_CASHCOUPONID`,
	ADD INDEX `INX_WEIXIN_CASHCOUPONHISTORY_CASHCOUPONID` (`cashcouponid`);
