
CREATE TABLE `weixin_unifiedorder` (
	`ID` VARCHAR(32) NULL DEFAULT NULL,
	`appid` VARCHAR(32) NULL DEFAULT NULL COMMENT '公众账号ID',
	`mch_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '商户号',
	`device_info` VARCHAR(32) NULL DEFAULT NULL COMMENT '设备号',
	`nonce_str` VARCHAR(32) NULL DEFAULT NULL COMMENT '随机字符窜',
	`sign` VARCHAR(32) NULL DEFAULT NULL COMMENT '签名',
	`body` VARCHAR(127) NULL DEFAULT NULL COMMENT '商品描述',
	`attach` VARCHAR(127) NULL DEFAULT NULL COMMENT '附加数据',
	`out_trade_no` VARCHAR(32) NULL DEFAULT NULL COMMENT '商户订单号',
	`total_fee` VARCHAR(32) NULL DEFAULT NULL COMMENT '总金额',
	`spbill_create_ip` VARCHAR(16) NULL DEFAULT NULL COMMENT '终端IP',
	`time_start` VARCHAR(20) NULL DEFAULT NULL COMMENT '交易起始时间',
	`time_expire` VARCHAR(20) NULL DEFAULT NULL COMMENT '交易结束时间',
	`goods_tag` VARCHAR(32) NULL DEFAULT NULL COMMENT '商品标记',
	`notify_url` VARCHAR(256) NULL DEFAULT NULL COMMENT '通知地址',
	`trade_type` VARCHAR(16) NULL DEFAULT NULL COMMENT '交易类型',
	`openid` VARCHAR(128) NULL DEFAULT NULL COMMENT '用户标识',
	`product_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '商品ID'
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
CREATE TABLE `weixin_unifiedorderresult` (
	`ID` VARCHAR(32) NULL DEFAULT NULL,
	`return_code` VARCHAR(16) NULL DEFAULT NULL COMMENT '返回状态码',
	`return_msg` VARCHAR(128) NULL DEFAULT NULL COMMENT '换回信息',
	`appid` VARCHAR(32) NULL DEFAULT NULL COMMENT '公众账号ID',
	`mch_id` VARCHAR(32) NULL DEFAULT NULL COMMENT '商户号',
	`device_info` VARCHAR(32) NULL DEFAULT NULL COMMENT '设备号',
	`nonce_str` VARCHAR(32) NULL DEFAULT NULL COMMENT '随机字符窜',
	`sign` VARCHAR(32) NULL DEFAULT NULL COMMENT '签名',
	`result_code` VARCHAR(16) NULL DEFAULT NULL COMMENT '业务结果',
	`err_code` VARCHAR(32) NULL DEFAULT NULL COMMENT '错误代码',
	`err_code_des` VARCHAR(32) NULL DEFAULT NULL COMMENT '错误代码描述',
	`trade_type` VARCHAR(32) NULL DEFAULT NULL COMMENT '交易类型',
	`prepay_id` VARCHAR(50) NULL DEFAULT NULL COMMENT '预支付ID',
	`code_url` VARCHAR(32) NULL DEFAULT NULL COMMENT '二维码链接',
	`out_trade_no` VARCHAR(40) NULL DEFAULT NULL COMMENT '商户订单号'
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
CREATE TABLE `weixin_notify` (
	`ID` VARCHAR(32) NULL DEFAULT NULL,
	`return_code` VARCHAR(20) NULL DEFAULT NULL COMMENT '返回状态码',
	`return_msg` VARCHAR(250) NULL DEFAULT NULL COMMENT '返回信息 ',
	`appid` VARCHAR(40) NULL DEFAULT NULL COMMENT '公众账号ID',
	`mch_id` VARCHAR(40) NULL DEFAULT NULL COMMENT '商户号',
	`device_info` VARCHAR(40) NULL DEFAULT NULL COMMENT '设备号',
	`nonce_str` VARCHAR(40) NULL DEFAULT NULL COMMENT '随机字符串',
	`sign` VARCHAR(40) NULL DEFAULT NULL COMMENT '签名',
	`result_code` VARCHAR(40) NULL DEFAULT NULL COMMENT '业务结果',
	`err_code` VARCHAR(40) NULL DEFAULT NULL COMMENT '错误代码',
	`err_code_des` VARCHAR(150) NULL DEFAULT NULL COMMENT '错误代码描述',
	`openid` VARCHAR(150) NULL DEFAULT NULL COMMENT '用户标识',
	`is_subscribe` VARCHAR(5) NULL DEFAULT NULL COMMENT '是否关注公众账号',
	`trade_type` VARCHAR(20) NULL DEFAULT NULL COMMENT '交易类型',
	`bank_type` VARCHAR(20) NULL DEFAULT NULL COMMENT '付款银行',
	`total_fee` VARCHAR(30) NULL DEFAULT NULL COMMENT '总金额',
	`coupon_fee` VARCHAR(30) NULL DEFAULT NULL COMMENT '现金券金额',
	`fee_type` VARCHAR(10) NULL DEFAULT NULL COMMENT '货币种类',
	`transaction_id` VARCHAR(40) NULL DEFAULT NULL COMMENT '微信支付订单号',
	`attach` VARCHAR(140) NULL DEFAULT NULL COMMENT '商家数据包 ',
	`time_end` VARCHAR(30) NULL DEFAULT NULL COMMENT '支付完成时间',
	`out_trade_no` VARCHAR(40) NULL DEFAULT NULL COMMENT '商户订单号 ',
	`cash_fee` VARCHAR(30) NULL DEFAULT NULL COMMENT '现金'
)
COMMENT='微信支付后台通用通知接口'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

